### ISSUE TITLE
No module named 'qgis._3d'

### ISSUE THREAD

**Issue by jakimowb** [conda-forge/qgis-feedstock#149]
Issue:

Opening the QGIS python console (CTRL+ALT+P) fails with an `ModuleNotFoundError: No module named 'qgis._3d'`error:

````
Traceback (most recent call last):
  File "D:\miniconda3\envs\qgis_stable\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "", line 1, in 
  File "D:/miniconda3/envs/qgis_stable/Library/./python\qgis\utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgis._3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 2, in 
  File "D:/miniconda3/envs/qgis_stable/Library/./python\console\console.py", line 47, in show_console
    _console = PythonConsole(parent)
  File "D:/miniconda3/envs/qgis_stable/Library/./python\console\console.py", line 83, in __init__
    self.console = PythonConsoleWidget(self)
  File "D:/miniconda3/envs/qgis_stable/Library/./python\console\console.py", line 113, in __init__
    self.shell = ShellScintilla(self)
  File "D:/miniconda3/envs/qgis_stable/Library/./python\console\console_sci.py", line 104, in __init__
    self.runsource(line)
  File "D:/miniconda3/envs/qgis_stable/Library/./python\console\console_sci.py", line 679, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "D:\miniconda3\envs\qgis_stable\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "D:\miniconda3\envs\qgis_stable\lib\code.py", line 94, in runcode
    self.showtraceback()
  File "D:\miniconda3\envs\qgis_stable\lib\code.py", line 148, in showtraceback
    sys.excepthook(ei[0], ei[1], last_tb)
  File "D:/miniconda3/envs/qgis_stable/Library/./python\console\console_sci.py", line 675, in excepthook
    self.write("".join(traceback.format_exception(etype, value, tb)))
  File "D:/miniconda3/envs/qgis_stable/Library/./python\console\console_sci.py", line 660, in write
    sys.stderr.write(txt)
AttributeError: 'NoneType' object has no attribute 'write'

````

<br/>
QGIS 
<details>

QGIS version | 3.14.16-Pi | QGIS code branch | Release 3.14
-- | -- | -- | --
Compiled against Qt | 5.12.9 | Running against Qt | 5.12.9
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 5.0.0
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.1 | Running against PROJ | Rel. 7.1.1, September 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins |  

</details>

Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
boost-cpp                 1.74.0               hd4e6614_0    conda-forge
brotlipy                  0.7.0           py38hab1e662_1001    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            hf56ce5a_1006    conda-forge
certifi                   2020.6.20        py38h9bdc248_2    conda-forge
cffi                      1.14.3           py38h0e640b1_1    conda-forge
cfitsio                   3.470                hbbe6aef_7    conda-forge
chardet                   3.0.4           py38h9bdc248_1008    conda-forge
coverage                  5.3              py38h1e8a9f7_1    conda-forge
cryptography              3.1.1            py38h0e640b1_1    conda-forge
curl                      7.71.1               h4b64cdc_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
docutils                  0.16             py38h32f6830_1    conda-forge
exiv2                     0.27.1               hfa2c1cf_0    conda-forge
expat                     2.2.9                h33f27b4_2    conda-forge
freetype                  2.10.4               hd328e21_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
future                    0.18.2           py38h32f6830_2    conda-forge
gdal                      3.1.4            py38h8f7194f_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.6.0                h8884d1a_3    conda-forge
gettext                   0.19.8.1          hfbb10ce_1004    conda-forge
git-lfs                   1.6                      pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.9                    pypi_0    pypi
glib                      2.66.2               ha925a31_0    conda-forge
gsl                       2.6                  h86b8168_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_h89124ea_1110    conda-forge
httplib2                  0.18.1             pyh9f0ad1d_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       67.1                 h33f27b4_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2019.4                      245
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
kealib                    1.4.13               h3b59ab9_1    conda-forge
kiwisolver                1.2.0            py38h95a2b95_1    conda-forge
krb5                      1.17.1               hc04afaa_3    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  10.0.1          default_hf44288c_1    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libgdal                   3.1.4                h0e5aa5a_0    conda-forge
libglib                   2.66.2               h31c07e1_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             he9e54da_1012    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h2ee746f_106    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libpq                     12.3                 hd9aa61d_2    conda-forge
libprotobuf               3.13.0.1             h200bbdf_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             5.0.0                hf693123_0    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
libzip                    1.5.1             h8f0db0c_1005    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py38hab1e662_2    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py38h6584adb_1    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py38hfa6e2cd_0    conda-forge
mock                      4.0.2            py38h32f6830_1    conda-forge
msys2-conda-epoch         20160418                      1
nose2                     0.9.2                      py_0    conda-forge
numpy                     1.19.2           py38hdf1ac2f_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
owslib                    0.20.0                     py_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pillow                    8.0.1            py38h7011068_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.38.0            hfa6e2cd_1003    conda-forge
plotly                    4.12.0             pyh9f0ad1d_0    conda-forge
poppler                   0.89.0               h5d62644_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 he14cc48_2    conda-forge
proj                      7.1.1                h7d85306_3    conda-forge
psycopg2                  2.8.6            py38hba49e27_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pyopengl                  3.1.5                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38hbdc76b6_3    conda-forge
pyqt                      5.12.3           py38h7ae7562_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1            py38h9bdc248_2    conda-forge
python                    3.8.6           h60c2a47_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38hab1e662_1    conda-forge
qca                       2.2.1                hd7ce7fb_3    conda-forge
qgis                      3.14.16          py38ha5722f9_2    conda-forge
qjson                     0.9.0             hd7ce7fb_1006    conda-forge
qscintilla2               2.11.2           py38h19e3e1c_2    conda-forge
qt                        5.12.9               hb2cf2c5_0    conda-forge
qtkeychain                0.11.1               h265ddaf_0    conda-forge
qtlocation                5.12.9               ha925a31_0    conda-forge
qwt                       6.1.5                h265ddaf_0    conda-forge
qwtpolar                  1.1.1                hd7ce7fb_7    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
scikit-learn              0.23.2           py38hf00eced_0    conda-forge
scipy                     1.5.0            py38h9439919_0
setuptools                49.6.0           py38h9bdc248_2    conda-forge
sip                       4.19.24          py38h7ae7562_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4                    pypi_0    pypi
sqlite                    3.33.0               he774522_1    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    2.1.2                hfabd47f_0    conda-forge
tk                        8.6.10               he774522_1    conda-forge
tornado                   6.0.4            py38h1e8a9f7_2    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
win_inet_pton             1.1.0            py38h32f6830_1    conda-forge
wincertstore              0.2             py38h32f6830_1005    conda-forge
xerces-c                  3.2.3                ha925a31_1    conda-forge
xmlrunner                 1.7.7                      py_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
    active environment : qgis_stable
    active env location : D:\miniconda3\envs\qgis_stable
            shell level : 2
       user config file : C:\Users\username\.condarc
 populated config files :
          conda version : 4.9.0
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : D:\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\miniconda3\pkgs
                          C:\Users\username\.conda\pkgs
                          C:\Users\username\AppData\Local\conda\conda\pkgs
       envs directories : D:\miniconda3\envs
                          C:\Users\username\.conda\envs
                          C:\Users\username\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

**Comment by jakimowb** [comment]
Seems to be related to #89 and may be caused by the `WITH_3D=FALSE` flag.

**Comment by SrNetoChan** [comment]
@jakimowb this should work fine on 3.16, but we are missing the windows builds... :(

**Comment by SrNetoChan** [comment]
Everything works fine now, even in windows. I am closing this one.
